#!/bin/sh
#
# $Id: $
#
version=$(cat conf-version)

verbose=0
while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    *) optarg=
	;;
    esac

    case "$1" in
    --verbose)
	verbose=1
    ;;
    --clean)
	clean="--clean"
    ;;
    --release=*)
	release=$optarg
    ;;
    *)
    echo "invalid option [$1]"
    read key
    usage 1
    ;;
    esac

    shift
done

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi

make -s lcd-daemon.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 0
fi

if [ $copy_src -eq 1 ] ; then
	if [ ! -d ../stage ] ; then
		mkdir ../stage
	fi
	if [ $? -ne 0 ] ; then
		exit 1
	fi
	# /usr/local/src
	cd ..
	echo "Preparing lcd-daemon-"$version""
	/bin/cp -rp lcd-daemon stage/lcd-daemon-"$version"
	# /usr/local/src/stage/lcd-daemon-$version
	cd stage/lcd-daemon-$version
	echo "Cleaning lcd-daemon-"$version""
	make -s clean >/dev/null 2>&1
	make -s distclean >/dev/null 2>&1
	/bin/rm -rf autom4te.cache .deps src/config.log
	# /usr/local/src/stage/
	cd ..
	echo "Archiving lcd-daemon-"$version".tar.gz in `pwd`"
	tar \
		--exclude="lcd-daemon-$version/.git" \
		--exclude="lcd-daemon-$version/debian"  \
		-cf - lcd-daemon-"$version" \
		| gzip -c > $rpmbuild/SOURCES/lcd-daemon-"$version".tar.gz
	/bin/rm -rf lcd-daemon-"$version"
fi

dist=`uname -r |cut -d . -f4`
if [ -z "$release" ] ; then
	if [ -f /usr/bin/gpio ] ; then
		mdist=$(rpm -qf /usr/bin/gpio|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $mdist" ] ; then
			mversion=$(rpm -qf /usr/bin/gpio|cut -d- -f2)
			if [ "$mversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/gpio | cut -d- -f3 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi

# /usr/local/src/
cd ..
echo -n "Build RPM for lcd-daemon-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat lcd-daemon-"$version"/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		cd lcd-daemon
		echo 1.$release > conf-release
		make -s lcd-daemon.spec
		cp lcd-daemon.spec /tmp
		make -C debian -s
		cd ../..
	else
		cp lcd-daemon/lcd-daemon.spec /tmp
	fi
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	if [ $verbose -eq 0 ] ; then
		echo "rpmbuild -ba $clean --quiet /tmp/lcd-daemon.spec"
		rpmbuild -ba $clean --quiet /tmp/lcd-daemon.spec
	else
		echo "rpmbuild -ba $clean --quiet /tmp/lcd-daemon.spec"
		rpmbuild -ba $clean /tmp/lcd-daemon.spec
	fi
	if [ $? -eq 0 ] ; then
		/bin/rm /tmp/lcd-daemon.spec
		rpm --addsign \
			$rpmbuild/RPMS/$build_arch/lcd-daemon-"$version"-1."$release".$dist.$build_arch.rpm 
		echo -n "RPM lint for lcd-daemon-"$version"-1."$release" (Y/N) - "
		read key
		if [ " $key" = " Y" -o " $key" = " y" ] ; then
			(
			for i in lcd-daemon
			do
				echo $i
				rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
			echo ------------------------
			done
			echo lcd-daemon-"$version"-"1.$release".$dist.src.rpm
			rpmlint $rpmbuild/SRPMS/lcd-daemon-"$version"-"1.$release".$dist.src.rpm
			echo ------------------------
			) 2>&1 | less
		fi
	else
		/bin/rm /tmp/lcd-daemon.spec
	fi
else
	/bin/rm -rf /tmp/lcd-daemon-"$version"
fi

if [ $copy_src -eq 1 ] ; then
	echo -n "Remove Source (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		/bin/rm -f $rpmbuild/SOURCES/lcd-daemon-"$version".tar.gz
	fi
fi
