.\" vim: tw=75
.LL 1i
.TH pilcd 1
.SH NAME
pilcd \- Print text on LCD Displays with Hitachi 44780 controller

.SH SYNOPSYS
\fBpilcd\fR [-s] [-c clear_type] -r rownum message
.nf
or
\fBpilcd\fR -c 4 | -c 5 | -c 6
.fi

.SH DESCRIPTION
\fBpilcd(1)\fR communicates with \fBlcd-daemon\fR(8) to print text on 20x4
or 16x2 LCD displays with Hitachi 44780 controllers. It uses a named pipe
to send messages to \fBlcd-daemon\fR(8). The default named pipe is
\fIrundir/lcd-daemon/lcdfifo\fR which can be changed by setting
\fBLCDFIFO\fR environment variable. \fIrundir\fR is /run, /var/run or /tmp
depending on your system.

\fBpicld\fR(1) uses the following format for the message written to the
named pipe (here <sp> stands for the white space character)

.EX
\fIrownum\fR<sp>\fIscroll\fR<sp>\fIclear\fR:\fImessage\fR
.EE

where
.TP
\fIscroll\fR
value can be 0 or 1. 1 turns on scrolling
.TP
\fIrownum\fR
value can be 0 or 1 for 16x2 display or 0, 1, 2 or 3 for 20x4 display.
.TP
\fIclear\fR
The following values are supported for \fIclear\fR
.EX
1 clear the screen
2 clear and initialize
3 initializing LCD display
4 clear screen without displaying text
5 clear and initialize screen without displaying text
6 initialize screen without displaying text
.EE
.TP
\fImessage\fR
Here \fImessage\fR is any string specified as a single or multiple
arguments.

.SH OPTIONS
.TP 4
\fB\-s\fR 
Scrolls the message \fImessage\fR

.TP
\fB\-c\fR \fIclear_type\fR
Clears the LCD display before displaying text. You can give the following
values

.EX
1 clear the screen
2 clear and initialize
3 initializing LCD display
4 clear screen without displaying text
5 clear and initialize screen without displaying text
6 initialize screen without displaying text
.EE

.TP
\fB\-r\fR \fIrownum\fR
The row on which to print the text. Values are 0, 1, 2 or 3

.TP
\fImessage\fR
The text message to display on the screen.

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. A diagnostic message is
printed if pilcd encounters any error. If any systerm error is encountered,
the return value will be 111.

.SH AUTHORS
Manvendra Bhangui <lcd-daemon@indimail.org>

.SH "SEE ALSO"
supervise(8), svc(8), envdir(8), multilog(8), lcd-daemon(8),
notify-daemon(8)
